# Physics 404/604

## Computational Physics (Spring 2018)

## BPB-250, Mon./Wed. 2:30-3:45 pm

| Instructor | Prof. Zhaohuan Zhu                 |
| ---------- | :--------------------------------- |
| Email      | zhaohuan.zhu@unlv.edu              |
| Website    | http://www.physics.unlv.edu/~zhzhu |
| Office     | BPB 245                            |




# 2. How to represent numbers?



## 2.1 Integers:   

 [$-2^{n-1}$, $2^{n-1}$] where n is the number of bits used to store the signed integer
      
      Note that in python2 integer is either 4 bytes or 8 bytes. In python 3, integer can be any length as long as the memory allows. On the otherhand, some python libraries (e.g. numpy) donot support these very long integers. Remember only 19 digets integer

In [1]:
import numpy as np
a=np.array([2**63-1])
print(a.dtype)
print(a,bin(a[0]))
print(a+1,bin(a[0]+1))
    

int64
[9223372036854775807] 0b111111111111111111111111111111111111111111111111111111111111111
[-9223372036854775808] -0b1000000000000000000000000000000000000000000000000000000000000000


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:5: RuntimeWarning: overflow encountered in longlong_scalars


In [28]:
smaller = np.array([1.0])
bigger = np.array([1.0])
for i in range(0,2000):
    bigger = bigger*2
    smaller = smaller/2
    print((smaller,bigger,i))

(array([0.5]), array([2.]), 0)
(array([0.25]), array([4.]), 1)
(array([0.125]), array([8.]), 2)
(array([0.0625]), array([16.]), 3)
(array([0.03125]), array([32.]), 4)
(array([0.015625]), array([64.]), 5)
(array([0.0078125]), array([128.]), 6)
(array([0.00390625]), array([256.]), 7)
(array([0.00195312]), array([512.]), 8)
(array([0.00097656]), array([1024.]), 9)
(array([0.00048828]), array([2048.]), 10)
(array([0.00024414]), array([4096.]), 11)
(array([0.00012207]), array([8192.]), 12)
(array([6.10351562e-05]), array([16384.]), 13)
(array([3.05175781e-05]), array([32768.]), 14)
(array([1.52587891e-05]), array([65536.]), 15)
(array([7.62939453e-06]), array([131072.]), 16)
(array([3.81469727e-06]), array([262144.]), 17)
(array([1.90734863e-06]), array([524288.]), 18)
(array([9.53674316e-07]), array([1048576.]), 19)
(array([4.76837158e-07]), array([2097152.]), 20)
(array([2.38418579e-07]), array([4194304.]), 21)
(array([1.1920929e-07]), array([8388608.]), 22)
(array([5.96046448e-08]), arra

(array([6.81983153e-254]), array([1.46631188e+253]), 840)
(array([3.40991577e-254]), array([2.93262376e+253]), 841)
(array([1.70495788e-254]), array([5.86524752e+253]), 842)
(array([8.52478942e-255]), array([1.1730495e+254]), 843)
(array([4.26239471e-255]), array([2.34609901e+254]), 844)
(array([2.13119735e-255]), array([4.69219802e+254]), 845)
(array([1.06559868e-255]), array([9.38439604e+254]), 846)
(array([5.32799338e-256]), array([1.87687921e+255]), 847)
(array([2.66399669e-256]), array([3.75375841e+255]), 848)
(array([1.33199835e-256]), array([7.50751683e+255]), 849)
(array([6.65999173e-257]), array([1.50150337e+256]), 850)
(array([3.32999587e-257]), array([3.00300673e+256]), 851)
(array([1.66499793e-257]), array([6.00601346e+256]), 852)
(array([8.32498966e-258]), array([1.20120269e+257]), 853)
(array([4.16249483e-258]), array([2.40240539e+257]), 854)
(array([2.08124742e-258]), array([4.80481077e+257]), 855)
(array([1.04062371e-258]), array([9.60962154e+257]), 856)
(array([5.20311

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: RuntimeWarning: overflow encountered in multiply


(array([0.]), array([inf]), 1674)
(array([0.]), array([inf]), 1675)
(array([0.]), array([inf]), 1676)
(array([0.]), array([inf]), 1677)
(array([0.]), array([inf]), 1678)
(array([0.]), array([inf]), 1679)
(array([0.]), array([inf]), 1680)
(array([0.]), array([inf]), 1681)
(array([0.]), array([inf]), 1682)
(array([0.]), array([inf]), 1683)
(array([0.]), array([inf]), 1684)
(array([0.]), array([inf]), 1685)
(array([0.]), array([inf]), 1686)
(array([0.]), array([inf]), 1687)
(array([0.]), array([inf]), 1688)
(array([0.]), array([inf]), 1689)
(array([0.]), array([inf]), 1690)
(array([0.]), array([inf]), 1691)
(array([0.]), array([inf]), 1692)
(array([0.]), array([inf]), 1693)
(array([0.]), array([inf]), 1694)
(array([0.]), array([inf]), 1695)
(array([0.]), array([inf]), 1696)
(array([0.]), array([inf]), 1697)
(array([0.]), array([inf]), 1698)
(array([0.]), array([inf]), 1699)
(array([0.]), array([inf]), 1700)
(array([0.]), array([inf]), 1701)
(array([0.]), array([inf]), 1702)
(array([0.]), 

In [33]:
1.0+1e-16 == 1.0

True

## 2.2 Floating point numbers:

8 bytes  
One number in the memory   
ABBBBBBBBBBBCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

A: sign  
B: e  
C: $b_{52-i}$
i is the bit of C; the i of the leftmost C is 1; the i of the rightmost C is 52.

\begin{equation}  
x=(-1)^{sign}(1+\sum_{i=1}^{52} b_{52-i}2^{-i})2^{e-1023}
\end{equation}

In [2]:
import random
import numpy as np
import struct

In [3]:
def fextract(num):
    return ''.join(bin(c).replace('0b', '').rjust(8, '0') for c in struct.pack('!d', num))

In [17]:
struct.pack('!d',2e-1000)

b'\x00\x00\x00\x00\x00\x00\x00\x00'

In [9]:
fextract(2e-1023)

'0000000000000000000000000000000000000000000000000000000000000000'

In [4]:
num=1.0
print("%.31f  %s"%(num,fextract(num)[0]+' '+fextract(num)[1:12]+' '+fextract(num)[12:]))

1.0000000000000000000000000000000  0 01111111111 0000000000000000000000000000000000000000000000000000


In [5]:
num=0.5
print("%.31f  %s"%(num,fextract(num)[0]+' '+fextract(num)[1:12]+' '+fextract(num)[12:]))

0.5000000000000000000000000000000  0 01111111110 0000000000000000000000000000000000000000000000000000


In [6]:
num=0.75
print("%.31f  %s"%(num,fextract(num)[0]+' '+fextract(num)[1:12]+' '+fextract(num)[12:]))

0.7500000000000000000000000000000  0 01111111110 1000000000000000000000000000000000000000000000000000


In [98]:
num=0.2
print("%.31f  %s"%(num,fextract(num)[0]+' '+fextract(num)[1:12]+' '+fextract(num)[12:]))

0.2000000000000000111022302462516  0 01111111100 1001100110011001100110011001100110011001100110011010


Range 

[-$10^{308}$, -$10^{-324}$] [$10^{-324}$,10$^{308}$]

In [8]:
num=1.e-325 #underflow sometimes is treated as 0
print("%.19e  %s"%(num,fextract(num)[0]+' '+fextract(num)[1:12]+' '+fextract(num)[12:]))

0.0000000000000000000e+00  0 00000000000 0000000000000000000000000000000000000000000000000000


In [9]:
num=1.e-323
print("%.19e  %s"%(num,fextract(num)[0]+' '+fextract(num)[1:12]+' '+fextract(num)[12:]))

9.8813129168249308835e-324  0 00000000000 0000000000000000000000000000000000000000000000000010


In [113]:
num=1.e309 #overflow generates infinity
print("%.19e  %s"%(num,fextract(num)[0]+' '+fextract(num)[1:12]+' '+fextract(num)[12:]))

inf  0 11111111111 0000000000000000000000000000000000000000000000000000


In [127]:
num=1.7976931348e308 #overflow generates infinity
print("%.19e  %s"%(num,fextract(num)[0]+' '+fextract(num)[1:12]+' '+fextract(num)[12:]))

1.7976931347999999853e+308  0 11111111110 1111111111111111111111111111111110110011110001011011


In [1]:
# Write a code to determine the overflow and underflow limit to be accurate by a factor 2

under =1.
over =1.
for i in range(1100):
    under = under/2.
    over =over*2.
    print("Loop number %d, under %25.17e, over %25.17e"%(i,under,over))

Loop number 0, under   5.00000000000000000e-01, over   2.00000000000000000e+00
Loop number 1, under   2.50000000000000000e-01, over   4.00000000000000000e+00
Loop number 2, under   1.25000000000000000e-01, over   8.00000000000000000e+00
Loop number 3, under   6.25000000000000000e-02, over   1.60000000000000000e+01
Loop number 4, under   3.12500000000000000e-02, over   3.20000000000000000e+01
Loop number 5, under   1.56250000000000000e-02, over   6.40000000000000000e+01
Loop number 6, under   7.81250000000000000e-03, over   1.28000000000000000e+02
Loop number 7, under   3.90625000000000000e-03, over   2.56000000000000000e+02
Loop number 8, under   1.95312500000000000e-03, over   5.12000000000000000e+02
Loop number 9, under   9.76562500000000000e-04, over   1.02400000000000000e+03
Loop number 10, under   4.88281250000000000e-04, over   2.04800000000000000e+03
Loop number 11, under   2.44140625000000000e-04, over   4.09600000000000000e+03
Loop number 12, under   1.22070312500000000e-04, o

Machine Precision: 

In [43]:
num=1.0e-17
print("%.31f  %s"%(num,fextract(num)[0]+' '+fextract(num)[1:12]+' '+fextract(num)[12:]))

0.0000000000000000100000000000000  0 01111000110 0111000011101111010101000110010001101101010010010111


In [45]:
num=1.0+1.0e-17
print("%.31f  %s"%(num,fextract(num)[0]+' '+fextract(num)[1:12]+' '+fextract(num)[12:]))

1.0000000000000000000000000000000  0 01111111111 0000000000000000000000000000000000000000000000000000


In [16]:
num1 = 100.1
num2= 100.1+100.*1.0e-17
print("%.31f %.31f"%(num1,num2))

100.0999999999999943156581139191985 100.0999999999999943156581139191985


In [2]:
# determine your machine's precision

N = 60
eps =1.0

for i in range(N):
    eps = eps/2
    one_plus_eps = 1.0 + eps
    print('eps=',eps, 'one_plus_eps',one_plus_eps)

eps= 0.5 one_plus_eps 1.5
eps= 0.25 one_plus_eps 1.25
eps= 0.125 one_plus_eps 1.125
eps= 0.0625 one_plus_eps 1.0625
eps= 0.03125 one_plus_eps 1.03125
eps= 0.015625 one_plus_eps 1.015625
eps= 0.0078125 one_plus_eps 1.0078125
eps= 0.00390625 one_plus_eps 1.00390625
eps= 0.001953125 one_plus_eps 1.001953125
eps= 0.0009765625 one_plus_eps 1.0009765625
eps= 0.00048828125 one_plus_eps 1.00048828125
eps= 0.000244140625 one_plus_eps 1.000244140625
eps= 0.0001220703125 one_plus_eps 1.0001220703125
eps= 6.103515625e-05 one_plus_eps 1.00006103515625
eps= 3.0517578125e-05 one_plus_eps 1.000030517578125
eps= 1.52587890625e-05 one_plus_eps 1.0000152587890625
eps= 7.62939453125e-06 one_plus_eps 1.0000076293945312
eps= 3.814697265625e-06 one_plus_eps 1.0000038146972656
eps= 1.9073486328125e-06 one_plus_eps 1.0000019073486328
eps= 9.5367431640625e-07 one_plus_eps 1.0000009536743164
eps= 4.76837158203125e-07 one_plus_eps 1.0000004768371582
eps= 2.384185791015625e-07 one_plus_eps 1.000000238418579
eps= 1

In [34]:
# error in operations

num1 = 0.1
num2 = 0.2
num3 = 0.3
print("%.31f %.31f %.31f %.31f"%(num1,num2, num1+num2, num3))
print(" the relative of the difference is ",abs((num1+num2)/num3-1))

0.1000000000000000055511151231258 0.2000000000000000111022302462516 0.3000000000000000444089209850063 0.2999999999999999888977697537484
 the relative of the difference is  2.220446049250313e-16


In [33]:
num1 = 0.2000000000001
num2 = 0.2
num3 = 0.0000000000001
print("%.31f %.31f %.31f %.31f"%(num1,num2, num1-num2, num3))
print(" the relative of the difference is ",abs((num1-num2)/num3-1))

0.2000000000000999866855977415980 0.2000000000000000111022302462516 0.0000000000000999755833674953465 0.0000000000001000000000000000030
 the relative of the difference is  0.00024416632504653535


In [38]:
n = 1
for i in range(0,100):
    print("%.31f"%(1.0+n),i)
    n = n/2.0

2.0000000000000000000000000000000 0
1.5000000000000000000000000000000 1
1.2500000000000000000000000000000 2
1.1250000000000000000000000000000 3
1.0625000000000000000000000000000 4
1.0312500000000000000000000000000 5
1.0156250000000000000000000000000 6
1.0078125000000000000000000000000 7
1.0039062500000000000000000000000 8
1.0019531250000000000000000000000 9
1.0009765625000000000000000000000 10
1.0004882812500000000000000000000 11
1.0002441406250000000000000000000 12
1.0001220703125000000000000000000 13
1.0000610351562500000000000000000 14
1.0000305175781250000000000000000 15
1.0000152587890625000000000000000 16
1.0000076293945312500000000000000 17
1.0000038146972656250000000000000 18
1.0000019073486328125000000000000 19
1.0000009536743164062500000000000 20
1.0000004768371582031250000000000 21
1.0000002384185791015625000000000 22
1.0000001192092895507812500000000 23
1.0000000596046447753906250000000 24
1.0000000298023223876953125000000 25
1.0000000149011611938476562500000 26
1.000000007

## 2.3 How to calculate sin(x): When to stop
### 2.3.1 using built-in functions

In [209]:
import numpy as np
np.sin(5.8)

-0.46460217941375737

### 2.3.2 using summing series
\begin{equation}
{\rm sin} \,x=x-\frac{x^3}{3!}+\frac{x^5}{5!}-\frac{x^7}{7!} + ...
\end{equation}
or
\begin{equation}
{\rm sin} \,x \simeq \sum_{n=1}^{N}\frac{(-1)^{n-1}x^{2n-1}}{(2n-1)!}
\end{equation}

In [203]:
import numpy as np

def sin1(x, n):
    sin1 = 0.0
    for i in range(1,n+1):
        sin1+=(-1)**(i-1)*x**(2*i-1)/np.math.factorial(2*i-1)
    return sin1

In [212]:
import time
start_time = time.time()
print(sin1(5.8,20)) # compare with -0.46460217941375737
print("--- %s seconds ---" % (time.time() - start_time))

-0.4646021794137545
--- 0.00041103363037109375 seconds ---


### 2.3.3 using summing series but use relationship between different series
\begin{equation}
nth\, term=\frac{-x^2}{(2n-1)(2n-2)} \times(n-1)th\, term
\end{equation}

In [202]:
import numpy as np

def sin2(x, n):
    sin2 = 0.0
    nm1th = x
    sin2 = nm1th
    for i in range(2,n+1):
        nth = nm1th*(-x*x)/(2*i-1)/(2*i-2)
        sin2 += nth
        nm1th = nth
        print(i,sin2,nth)
    return sin2

In [201]:
import time
start_time = time.time()
print(sin2(5.8,20))
print("--- %s seconds ---" % (time.time() - start_time)) # compare with -0.46460217941375737

2 -26.718666666666667 -32.51866666666667
3 27.97773066666667 54.69639733333334
4 -15.831479006984129 -43.8092096736508
5 4.637157290538273 20.4686362975224
6 -1.6225238462676685 -6.259681136805941
7 -0.2726797857410539 1.3498440605266147
8 -0.4889119485796982 -0.21623216283864435
9 -0.4621691178521541 0.026742830727544104
10 -0.4647996114944774 -0.002630493642323344
11 -0.4645889214798875 0.0002106900145898983
12 -0.4646029286184069 -1.4007138519375849e-05
13 -0.46460214328484056 7.853335663196727e-07
14 -0.46460218091820404 -3.7633363491444145e-08
15 -0.4646021793591076 1.5590964875026861e-09
16 -0.4646021794155033 -5.63957052038606e-11
17 -0.46460217941370674 1.7965450028957105e-12
18 -0.46460217941375753 -5.07863646196737e-14
19 -0.46460217941375626 1.2826226019563238e-15
20 -0.4646021794137563 -2.91143214101287e-17
-0.4646021794137563
--- 0.002959012985229492 seconds ---


In [213]:
print(sin2(5.8,25)) 

2 -26.718666666666667 -32.51866666666667
3 27.97773066666667 54.69639733333334
4 -15.831479006984129 -43.8092096736508
5 4.637157290538273 20.4686362975224
6 -1.6225238462676685 -6.259681136805941
7 -0.2726797857410539 1.3498440605266147
8 -0.4889119485796982 -0.21623216283864435
9 -0.4621691178521541 0.026742830727544104
10 -0.4647996114944774 -0.002630493642323344
11 -0.4645889214798875 0.0002106900145898983
12 -0.4646029286184069 -1.4007138519375849e-05
13 -0.46460214328484056 7.853335663196727e-07
14 -0.46460218091820404 -3.7633363491444145e-08
15 -0.4646021793591076 1.5590964875026861e-09
16 -0.4646021794155033 -5.63957052038606e-11
17 -0.46460217941370674 1.7965450028957105e-12
18 -0.46460217941375753 -5.07863646196737e-14
19 -0.46460217941375626 1.2826226019563238e-15
20 -0.4646021794137563 -2.91143214101287e-17
21 -0.4646021794137563 5.971986416077618e-19
22 -0.4646021794137563 -1.112389939295964e-20
23 -0.4646021794137563 1.8899392706018298e-22
24 -0.4646021794137563 -2.940682

When to stop?  

The new term is smaller than the round-off error  
|nth term/sum|<1.e-16


In [187]:
import numpy as np

def sin3(x, n):
    sin3 = 0.0
    nm1th = x
    sin3 = nm1th
    for i in range(2,n+1):
        nth = nm1th*(-x*x)/(2*i-1)/(2*i-2)
        sin3 += nth
        nm1th = nth
        print(i,sin3,nth)
        if abs(nth/sin3)<1.e-16:
            return sin3
    return sin3

In [197]:
import time
start_time = time.time()
print(sin3(5.8,23))
print("--- %s seconds ---" % (time.time() - start_time))

2 -26.718666666666667 -32.51866666666667
3 27.97773066666667 54.69639733333334
4 -15.831479006984129 -43.8092096736508
5 4.637157290538273 20.4686362975224
6 -1.6225238462676685 -6.259681136805941
7 -0.2726797857410539 1.3498440605266147
8 -0.4889119485796982 -0.21623216283864435
9 -0.4621691178521541 0.026742830727544104
10 -0.4647996114944774 -0.002630493642323344
11 -0.4645889214798875 0.0002106900145898983
12 -0.4646029286184069 -1.4007138519375849e-05
13 -0.46460214328484056 7.853335663196727e-07
14 -0.46460218091820404 -3.7633363491444145e-08
15 -0.4646021793591076 1.5590964875026861e-09
16 -0.4646021794155033 -5.63957052038606e-11
17 -0.46460217941370674 1.7965450028957105e-12
18 -0.46460217941375753 -5.07863646196737e-14
19 -0.46460217941375626 1.2826226019563238e-15
20 -0.4646021794137563 -2.91143214101287e-17
-0.4646021794137563
--- 0.0029981136322021484 seconds ---


# How to calculate $e^x$ : very careful with subtraction

\begin{equation}
e^x=1+x+\frac{x^2}{2!}+\frac{x^3}{3!}+...
\end{equation}

In [221]:
import numpy as np
print(np.e,np.e**(-1))

2.718281828459045 0.36787944117144233


In [217]:
import numpy as np

def exp1(x, n):
    exp1 = 0.0
    for i in range(n):
        exp1+=x**i/np.math.factorial(i)
    return exp1

In [228]:
exact=np.e**(-1)
print((exp1(-1,8)-exact)/exact)
print((1./exp1(1,8)-exact)/exact) # using 1/e^1 avoids subtraction cancelation 

-6.061310256546751e-05
1.0249301721642577e-05


In [42]:
def exp2(x,n):
    nth = 1.0
    expn = 1.0
    for i in range(1,n):
        nth = nth*x/i
        expn += nth
    return expn

In [43]:
exact=np.e**(-1)
print((exp2(-1,8)-exact)/exact)
print((1./exp2(1,8)-exact)/exact)

-6.061310256546751e-05
1.0249301721642577e-05
